In [4]:
import numpy as np
from gaussian_pos_prob import gaussian_pos_prob

M = 2
N = 4
K = 3

# M-by-K
Mu = np.asarray([[0,0,0],[0,0,0]])
# M-by-M-by-K
Sigma = np.asarray([[[1, 0.5, 2],[0, 0, 0]],[[0, 0, 0],[1, 0.5, 2]]])
# 1-by-K
Phi = np.asarray([0.5,0.5,0.5])
# M-by-N
X = np.asarray([[0, 1, -1, 2],[0, 1, -1, 2]])

print(gaussian_pos_prob(X, Mu, Sigma, Phi))

[[1.59154943e-01 3.18309886e-01 7.95774715e-02]
 [5.85498315e-02 4.30785586e-02 4.82661763e-02]
 [5.85498315e-02 4.30785586e-02 4.82661763e-02]
 [2.91502447e-03 1.06781071e-04 1.07696397e-02]]
